"use client";

import { useState, useEffect } from "react";
import { Share2, Twitter, Copy, Check } from "lucide-react";

/**
 * Share button that copies a link to the user's OG share card.
 * The card is generated by /api/og/share and renders beautifully on Twitter/LinkedIn.
 */
export function ShareCard({ type = "stats" }: { type?: "stats" | "twin" | "report" }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [origin, setOrigin] = useState("");

  useEffect(() => {
    setOrigin(window.location.origin);
  }, []);

  const shareUrl = origin ? `${origin}/share` : "";
  const tweetUrl = shareUrl
    ? `https://twitter.com/intent/tweet?text=${encodeURIComponent("My coding stats on Aztrx 🚀")}&url=${encodeURIComponent(shareUrl)}`
    : "";

  function copyLink() {
    if (!shareUrl) return;
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2 font-manrope text-sm text-white transition-colors hover:bg-white/[0.08]"
      >
        <Share2 size={14} />
        Share
      </button>

      {open && (
        <div className="absolute right-0 top-full z-20 mt-2 flex flex-col gap-1 rounded-xl border border-white/10 bg-[#0e0f14] p-2 shadow-xl">
          <a
            href={tweetUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 rounded-lg px-4 py-2.5 font-inter text-sm text-white transition-colors hover:bg-white/5"
          >
            <Twitter size={14} className="text-[#1DA1F2]" /> Share on X
          </a>
          <button
            onClick={copyLink}
            className="flex items-center gap-2 rounded-lg px-4 py-2.5 font-inter text-sm text-white transition-colors hover:bg-white/5"
          >
            {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} className="text-neutral-400" />}
            {copied ? "Copied!" : "Copy link"}
          </button>
        </div>
      )}
    </div>
  );
}
